### PR TITLE
fixed crashbug with empty string

### PR DESCRIPTION
**Pull request by roddi**
please accept this patch. 
   Thanks Roddi

### CODE REVIEW

**Comment by vmg** [comment]
Hey, sorry I've overlooked this. I don't quite like the fix -- can you tell me why is `bufputs` called with a NULL string? I think it'd be better if we fixed that instead. :)

**Comment by roddi** [comment]
Hi tanoku,

in my code (when using sundown) I accidentally called it with a NULL string (fixed by now). Since all other methods of the buffer module check for NULL pointers I thought that this was an oversight that should be fixed. 

Is there a reason, that buffputs() should not check its parameters but crash instead? Shouldn't I use buffputs() in the first place (as a client)?

Regards 
   Roddi

**Comment by vmg** [comment]
:+1: I've merged a different version of this, that asserts the buffer and the buffer allocation size uniformly for all buffer calls. Thanks for spotting this!

**Comment by roddi** [comment]
Good solution, Thanks!

**Pull request closed without merging**
