### PR TITLE
added Xcode project, objC osx & iOS wrapper class and two short demo apps

### PR DESCRIPTION
**Pull request by Daij-Djan**
Signed-off-by: Dominik Pich Dominik@pich.info

### CODE REVIEW

**Comment by gampleman** [comment]
The ObjC API looks rather weird to me. I don't think the from file and from URL methods are really necessary, it's trivial to implement. On the other hand having some way to set options would be very useful. A really cool project would be hacking in a way to be able to override parts of the renderer via inheritance similarly to how redcarpet does it.

**Comment by Daij-Djan** [comment]
yes they aren't needed but look nice :) no weird C code anywhere ;) 
anyway I guess the 'main thing' is the short demo app

**Comment by mildsunrise** [comment]
:-1:

No samples here, please. This is just the "core" library.

This is **open-source & multiplatform**. The samples should also be.
Besides, the platform(s) these demos target is **closed-source** (Mac OSX, iOS, XCode, Darwin, ...).

Better, publish them on a separate repo.
Same applies to the wrappers/bindings. Then,
propose to add a _link_ to them here. IMHO.

Thanks.

**Comment by Daij-Djan** [comment]
I dont agree with you but Im not devasted by your ideas :D Ill keep a separate repo and no prob :)

**Pull request closed without merging**
