### PR TITLE
Fix compilation under Visual Studio

### PR DESCRIPTION
**Pull request by andrew-d**
Hello,

This commit should fix compilation under Windows using Visual Studio.  It does not modify any code otherwise.

Thanks :-)

### CODE REVIEW

**Comment by andrew-d** [comment]
Also, I did see the other commit with the project file, but I felt that this was a little less intrusive.

**Comment by andrew-d** [comment]
Bump.  Sundown is used as part of [misaka](https://github.com/FSX/misaka), and I'd really love to be able to use it on Windows.  You're welcome to mark support "experimental", if you wish.  And there's no changes to the code at all if you're not compiling on Windows.

**Comment by andre-d** [comment]
Seeing your username on my feed makes me do a double take

**Comment by andrew-d** [comment]
Hahahaha:-P

I'll admit, seeing the notification email from GitHub about that comment ("From: Andre d") made ME do a double-take too!

**Comment by vmg** [comment]
Sorry for the delay, guys. I've just merged a simpler PR that doesn't include a compat-header -- I'd rather minimize the number of files in the library.

Please ping if compilation happens to break again under Windows.

**Comment by andrew-d** [comment]
Thanks - I can confirm that it builds on Windows now.

**Pull request closed without merging**
